# Generated by Django 3.0.3 on 2020-03-29 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collections',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='имя')),
                ('description', models.TextField(blank=True, max_length=250, verbose_name='описание')),
                ('year_of_issue_begin', models.IntegerField(default=0, verbose_name='год выпуска начало')),
                ('year_of_issue_end', models.IntegerField(default=0, verbose_name='год выпуска конец')),
                ('date_create', models.DateTimeField(auto_now=True, verbose_name='дата создания')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='имя')),
                ('description', models.TextField(blank=True, max_length=500, verbose_name='описание')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='цена продукта')),
                ('image', models.ImageField(blank=True, upload_to='product_images', verbose_name='изображение')),
                ('file_product', models.FileField(blank=True, upload_to='product_files', verbose_name='файл продукта')),
                ('year_of_issue', models.IntegerField(default=0, verbose_name='год выпуска')),
                ('date_create', models.DateTimeField(auto_now=True, verbose_name='дата создания')),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='имя')),
                ('description', models.TextField(blank=True, max_length=1500, verbose_name='описание')),
                ('date_create', models.DateTimeField(auto_now=True, verbose_name='дата создания')),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='имя')),
                ('date_create', models.DateTimeField(auto_now=True, verbose_name='дата создания')),
            ],
        ),
        migrations.CreateModel(
            name='TagsProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.Product')),
                ('id_tag', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.Tags')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='mainapp.ProductCategory'),
        ),
        migrations.AddField(
            model_name='product',
            name='colection',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.Collections'),
        ),
    ]
